# common parameters between envs
commons:
  architecture: x86_64
  root_device_type: ebs
  virtualization_type: hvm
  ami_type: amzn2
environments:
  # This DEV configuration specifies a server with two volumes and two users
  dev:
    server:
      instance_type: t2.micro
      min_count: 1
      max_count: 1
      volumes:
        - device: /dev/xvda
          size_gb: 10
          type: ext4
          mount: /
        - device: /dev/xvdf
          size_gb: 20
          type: xfs
          mount: /data
      users:
        - login: user1
          ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSNe+8eFme1ZxKd7fWbQjcx7sZ9FeXR4HMYPimpqVRLPkwIY9jP5NIRHw853jRTJK25kM7xAYu/hKwgG/eq1pYwD1PL+ECN5SBvPMpwyPeONBL49gncv2cqDslyO6KNtIol+iUZhQxXAaV15urAwAnLJH/qFcLq8ZzJKeVLYMmBtCPpUzdgCecQVCQG7MQRFRubLwHeQqAUcWfHb/bF+KPrHW1Aq0FO2hOllsI2f/JHCQiRMSCO+jfJFN6SMeyQnfK8oEQo6VPwvZEE9R8z9YmhEWZahWDxnv23xApfLSA4lWE+ug07dD47QT5z905ISqyFZbhDoffZBNQr7sALZaArpy18NXB2koiKFIJssgtQxzNDRGTrxRC+x4z+ZKjKYoZ3s/JpeXEpvfMD5wNRkPlMOcGsyi1d1AquqdzPGf/FTuwp9NHkB7HhWrM1CXiDGYtSjGH1Sl6cD5vCIVixzA8th0CXzakKZq1yKblQwwuPf8tz8Eut5W0GY7nPFwe9s3yzX0Jam2HTLkdXmgX6HpZ/Z20yNgOhjrjpdSjELohrK2zdhib/r9tZ8ojXJ/r6PefvUOt6WP02AuoooZ/hDZZ201ufamObs1lwvalhnuPEg0Nz1PW6Cy/ghRA6RTdCzNkLDjk1R2NCBQS4WCn10+16tDHqKxwL801CCCqn9cq2Q== user1
        - login: user2
          ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5vJYu7Kw5NCQ2QL42sDxWTl86Hqp+fq77nGRAwFgHHKErZhsNGUiL+MaaD75MLPYGPWiRoTp76Z+SzsgGGVvGpBD45g2OFXueauWGnFwiyr7SyhpbHMZl5+Mwh5S2gIIvZeu546exfyE2GtovWX3W/gwoctC4WplZ99JqxQoMwtKPDVlORfrBLhz5AEgU1lGHrSrN6e1QAc/jlyY/SRf/NO/zhP2J2w1GDJvjdtu6Rt+nv8Y/98/I88t+Czbeo3UgYLJ/OcBaMBhJ9wocnsW8hK81qYF6/ScTfCSOYHi4L1TQEfHuUdmqMO52xPCCYFfI+xMNJwThwKC1eJa/1UMpVjZpe/2maz83YHE7cbDqZOunNqIf4TNBxAA3fWkCpOti+tBH5ca2ipToMc8IoKsxe+lJoUmAOBpN+NQieT3nq0VoTHYymYjCWKB1DKBE5wbTLttHPADad5BS97ytS/uR5sjz1rYiVa6cHv5FRrxIDsApKELyX5Z19b0DjXy3rVSSfap9BUreGVm6p6w13VHkn/lDli/AqDsdPPDcTP80ZX9Ohco2esCQL5LXQy3Z/hvA127VR7ftCWb2b+es9fFPzgwkhAa5ZRi+UaKcdS2eG2v4kFGB9g5Mt8SIioReCyDvfSCNE+SedjPUfeFcYnzx/auRfdY0UZ7uKL/vn0zCew== user2
  prod:
    # This PROD configuration specifies a server with one volume and one user
    server:
      instance_type: t3.medium
      min_count: 2
      max_count: 5
      volumes:
        - device: /dev/xvdb
          size_gb: 20
          type: ext4
          mount: /
      users:
        - login: admin1
          ssh_key: ADMIN1_SSH_PUB_KEY admin1@localhost
